Testing Deploy and Github Actions: Freeing up port 3000 for the new site to build and update

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -53,7 +53,7 @@ jobs:
           fi
 
           echo "🚀 Restarting PM2 process..."
-          pm2 restart cloud-portfolio || echo "PM2 not found or not running. Skipping restart."
+          pm2 restart cloud-portfolio --update-env || echo "PM2 not found or not running. Skipping restart."
 
           echo "✅ Deployment completed successfully!"
         EOF
